apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: apps/argocd/overlays/dev
    repoURL: https://github.com/newcl/gitops.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    # manual for now  
    # automated:
    #   prune: true
    #   selfHeal: true
