apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: photoprism

resources:
  - namespace.yaml
  - pv-photos.yaml
  - pvc-photos.yaml
  - pv-storage.yaml
  - pvc-storage.yaml
  - photoprism-deployment.yaml
  - photoprism-service.yaml
  - photoprism-ingress.yaml 