apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-photos-pv
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /home/liang/photos
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - u1 