apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-photos
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: local-path
  volumeName: photoprism-photos-pv 