apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
    environment: dev
data:
  server.insecure: "true"
  # server.rootpath: "/"
  # server.basehref: "/"
  # server.enable.proxy.extension: "true"
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      # - Endpoints  <-- This line being commented out is key
      - EndpointSlice
      clusters:
      - "*"