apiVersion: v1
kind: Service
metadata:
  name: fallback-service
  namespace: argocd
spec:
  selector:
    app: fallback
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fallback
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fallback
  template:
    metadata:
      labels:
        app: fallback
    spec:
      containers:
        - name: fallback
          image: nginx
          ports:
            - containerPort: 80