apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
    # traefik.ingress.kubernetes.io/router.middlewares: argocd-argocd-headers@kubernetescrd
    traefik.ingress.kubernetes.io/forwardedHeaders: "true"
    # ssl-redirect: "true": Tells Traefik to redirect HTTP to HTTPS. In your case, you probably do NOT want this, since Cloudflare already handles HTTPS and your internal traffic is HTTP.
    # traefik.ingress.kubernetes.io/ssl-redirect: "true"


    # protocol: "https": Tells Traefik to use HTTPS to talk to the backend. You do NOT want this if Argo CD is only running HTTP.
    # traefik.ingress.kubernetes.io/protocol: "https"
spec:
  rules:
    - host: argo.elladali.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80