apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

# Patches for dev environment
patches:
  # Configure server to be accessible via LoadBalancer in dev
  - target:
      kind: Service
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer

  # Configure server to be insecure in dev (for easier access)
  - target:
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --insecure

# Common labels for dev environment
commonLabels:
  environment: dev 