apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: argocd-cmd-params-cm-patch.yaml

# Labels for dev environment
labels:
  - pairs:
      environment: dev 

      