# Middleware to set headers (keep this)
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: argocd-headers
#   namespace: argocd
# spec:
#   headers:
#     customRequestHeaders:
#       X-Forwarded-Proto: "https"
#       X-Forwarded-Host: "argo.elladali.com"