apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/managed-by: kustomize

# Configure ArgoCD server
patches:
  - target:
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --insecure
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --rootpath=/
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --basehref=/

  # Ensure the service is accessible within the cluster
  - target:
      kind: Service
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: replace
        path: /spec/ports/0/name
        value: http
      - op: replace
        path: /spec/ports/0/port
        value: 80
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8080 