apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - ../../base

patches:
  - target:
      kind: Application
      name: immich
    patch: |-
      - op: replace
        path: /spec/source/path
        value: apps/immich/overlays/dev
      - op: replace
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "0"

helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    version: 0.1.0
    releaseName: immich
    namespace: immich
    valuesInline:
      global:
        postgresql:
          enabled: false
      externalDatabase:
        type: postgresql
        host: "192.168.1.50"  # Replace with your PostgreSQL host
        port: 5432
        database: "photos"
        username: "photos"
        password: "123456"   # Replace with your password
      ingress:
        enabled: true
        className: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        hosts:
          - host: "photos.elladali.com"  # Replace with your domain
            paths:
              - path: /
                pathType: Prefix
        
      server:
        replicaCount: 2
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        persistence:
          enabled: true
          storageClass: "local-path"
          size: 300Gi  # Optimized for family photo sharing
      microservices:
        replicaCount: 2
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        persistence:
          enabled: true
          storageClass: "local-path"
          size: 300Gi
      machineLearning:
        replicaCount: 1
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      web:
        replicaCount: 2
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      redis:
        enabled: true
        auth:
          enabled: false
        master:
          persistence:
            enabled: true
            size: 10Gi
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "512Mi"
              cpu: "250m" 