prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
grafana:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
  ingress:
    enabled: true
    hosts:
      - gf.elladali.com
    paths:
      - /
    pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: "traefik" 