apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - namespace.yaml
  - pv-library.yaml
  - pvc-library.yaml

helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    version: 0.1.0
    releaseName: immich
    namespace: immich
    valuesInline:
      global:
        postgresql:
          enabled: false
      externalDatabase:
        type: postgresql
        host: "192.168.1.50"
        port: 5432
        database: "photos"
        username: "photos"
        password: "123456"
      env:
        DB_HOSTNAME: "192.168.1.50"
        DB_USERNAME: "photos"
        DB_DATABASE_NAME: "photos"
        DB_PASSWORD: "123456"
        DATABASE_URL: "postgresql://photos:123456@192.168.1.50:5432/photos"
        UPLOAD_LOCATION: "/usr/src/app/upload"
      redis:
        enabled: true
        architecture: standalone
        auth:
          enabled: false
      immich:
        persistence:
          library:
            existingClaim: immich-library
      proxy:
        ingress:
          main:
            enabled: true
            className: "nginx"
            hosts:
              - host: "photos.elladali.com"
                paths:
                  - path: /
                    pathType: Prefix 
