# Secret template for Immich database credentials
# This template shows the structure for storing sensitive data
# In production, use external secret management like Sealed Secrets or External Secrets Operator

apiVersion: v1
kind: Secret
metadata:
  name: immich-database
  namespace: immich
type: Opaque
data:
  host: MTkyLjE2OC4xLjUw
  port: NTQzMg==
  database: cGhvdG9z
  username: cGhvdG9z
  password: MTIzNDU2
---
# Example External Secret (if using External Secrets Operator)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-database
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: immich-database
    type: Opaque
  data:
    - secretKey: host
      remoteRef:
        key: immich/database/host
    - secretKey: port
      remoteRef:
        key: immich/database/port
    - secretKey: database
      remoteRef:
        key: immich/database/name
    - secretKey: username
      remoteRef:
        key: immich/database/username
    - secretKey: password
      remoteRef:
        key: immich/database/password 