apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          ports:
            - containerPort: 5678
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
          env:
            - name: DB_TYPE
              value: "sqlite"
            - name: GENERIC_TIMEZONE
              value: "America/Vancouver"
            - name: N8N_HOST
              value: "n.elladali.com"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: "https"
      volumes:
        - name: n8n-data
          hostPath:
            path: /data/n8n
            type: DirectoryOrCreate
