apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: mytube-dev
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mytube-dev
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytube-dev-huey
  namespace: mytube-dev
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret 